version: "3.8"

services:
  mysql:
    image: mysql:8.0.28
    container_name: cyan-raft-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mall
      MYSQL_CHARSET: utf8mb4
      MYSQL_COLLATION: utf8mb4_unicode_ci
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
  redis:
    image: redis:7.2.4
    container_name: cyan-raft-redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data